
services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"  
    environment:
      - MONGODB_URI=${MONGODB_URI} 
    depends_on:
      - mongo



      
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
