version: '3'
services:
  app:
    build: .
    ports:
      - "${PORT}:3000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=${MONGODB_URI}

  mongo:
   image: mongo:latest
   environment:
     MONGO_INITDB_ROOT_USERNAME: root
     MONGO_INITDB_ROOT_PASSWORD: adminroot123
   volumes:
     - mongodb_data:/data/db

volumes:
  mongodb_data: